### PR TITLE
Add a link to an alternative (and easier) way of installiing c&c parser

### PR DESCRIPTION
**Pull request by yuchenlin**

### CODE REVIEW

**Comment by yuchenlin** [comment]
Note that the original wiki/svn website for C&C is totally dead.

**Comment by pasmargo** [comment]
I didn't notice that the original C&C was not accessible. Thank you very much for the update and the alternative link!

We are getting good results with EasyCCG and I would suggest you also use that syntactic parser :)

Thank you for using ccg2lambda!

**Comment by yuchenlin** [comment]
Thanks for the suggestion and I will have a try! I just noticed that there was EasyCCG dependency in emnlp2017_sts.md.

**Comment by pasmargo** [comment]
EasyCCG allows to obtain n-best syntactic trees. Recently we extended ccg2lambda to do semantic parsing (and inference) with n-best candidates and you could benefit from that if you use EasyCCG.

Please let me know if that works for you!

**Comment by yuchenlin** [comment]
Sure! Thanks!

**Pull request merged**
